// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: DigitalGearKnob

#ifndef _DIGITALGEARKNOB_UI_H
#define _DIGITALGEARKNOB_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_InterfazMarchas.h"
#include "screens/ui_InterfazLogo.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * CargarBarra_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * AnimacinLogo_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_vwlogonegro466x466_png);    // assets/VWLogoNegro466x466.png

// FONTS
LV_FONT_DECLARE(ui_font_FuenteMarchas);
LV_FONT_DECLARE(ui_font_FuenteTexto);
LV_FONT_DECLARE(ui_font_FuenteVW);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
