// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: DigitalGearKnob

#ifndef UI_INTERFAZMARCHAS_H
#define UI_INTERFAZMARCHAS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_InterfazMarchas
extern void ui_InterfazMarchas_screen_init(void);
extern void ui_InterfazMarchas_screen_destroy(void);
extern lv_obj_t * ui_InterfazMarchas;
extern lv_obj_t * ui_CargaMarchas;
extern lv_obj_t * ui_BarraRotacion;
extern lv_obj_t * ui_Marchas;
extern lv_obj_t * ui_Scuffy;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Rotacion;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

