// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: DigitalGearKnob

#ifndef UI_INTERFAZLOGO_H
#define UI_INTERFAZLOGO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_InterfazLogo
extern void ui_InterfazLogo_screen_init(void);
extern void ui_InterfazLogo_screen_destroy(void);
extern lv_obj_t * ui_InterfazLogo;
extern lv_obj_t * ui_Logo;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

