// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: DigitalGearKnob

#include "../ui.h"

lv_obj_t * uic_Rotacion;
lv_obj_t * ui_InterfazMarchas = NULL;
lv_obj_t * ui_CargaMarchas = NULL;
lv_obj_t * ui_BarraRotacion = NULL;
lv_obj_t * ui_Marchas = NULL;
lv_obj_t * ui_Scuffy = NULL;
// event funtions

// build funtions

void ui_InterfazMarchas_screen_init(void)
{
    ui_InterfazMarchas = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_InterfazMarchas, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_InterfazMarchas, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InterfazMarchas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_InterfazMarchas, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_InterfazMarchas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CargaMarchas = lv_arc_create(ui_InterfazMarchas);
    lv_obj_set_width(ui_CargaMarchas, lv_pct(70));
    lv_obj_set_height(ui_CargaMarchas, lv_pct(70));
    lv_obj_set_align(ui_CargaMarchas, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_CargaMarchas, 0, 5);
    lv_arc_set_value(ui_CargaMarchas, 1);
    lv_obj_set_style_arc_color(ui_CargaMarchas, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_CargaMarchas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_CargaMarchas, lv_color_hex(0x0052FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_CargaMarchas, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_CargaMarchas, lv_color_hex(0x0052FF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CargaMarchas, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BarraRotacion = lv_spinner_create(ui_InterfazMarchas, 1000, 90);
    lv_obj_set_width(ui_BarraRotacion, lv_pct(100));
    lv_obj_set_height(ui_BarraRotacion, lv_pct(100));
    lv_obj_set_align(ui_BarraRotacion, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BarraRotacion, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_BarraRotacion, LV_DIR_BOTTOM);
    lv_obj_set_style_arc_width(ui_BarraRotacion, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_BarraRotacion, lv_color_hex(0x0052FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_BarraRotacion, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Marchas = lv_label_create(ui_InterfazMarchas);
    lv_obj_set_width(ui_Marchas, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Marchas, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Marchas, -10);
    lv_obj_set_y(ui_Marchas, 0);
    lv_obj_set_align(ui_Marchas, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Marchas, "1");
    lv_obj_set_style_text_color(ui_Marchas, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Marchas, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Marchas, &ui_font_FuenteMarchas, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scuffy = lv_label_create(ui_InterfazMarchas);
    lv_obj_set_width(ui_Scuffy, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Scuffy, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Scuffy, lv_pct(0));
    lv_obj_set_y(ui_Scuffy, lv_pct(30));
    lv_obj_set_align(ui_Scuffy, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Scuffy, "Scuffy");
    lv_obj_set_style_text_color(ui_Scuffy, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Scuffy, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Scuffy, &ui_font_FuenteTexto, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_Rotacion = ui_BarraRotacion;

}

void ui_InterfazMarchas_screen_destroy(void)
{
    if(ui_InterfazMarchas) lv_obj_del(ui_InterfazMarchas);

    // NULL screen variables
    ui_InterfazMarchas = NULL;
    ui_CargaMarchas = NULL;
    uic_Rotacion = NULL;
    ui_BarraRotacion = NULL;
    ui_Marchas = NULL;
    ui_Scuffy = NULL;

}
