// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: DigitalGearKnob

#include "../ui.h"

lv_obj_t * ui_InterfazLogo = NULL;
lv_obj_t * ui_Logo = NULL;
// event funtions

// build funtions

void ui_InterfazLogo_screen_init(void)
{
    ui_InterfazLogo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_InterfazLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_InterfazLogo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InterfazLogo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Logo = lv_img_create(ui_InterfazLogo);
    lv_img_set_src(ui_Logo, &ui_img_vwlogonegro466x466_png);
    lv_obj_set_width(ui_Logo, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Logo, LV_SIZE_CONTENT);    /// 150
    lv_obj_set_align(ui_Logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Logo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Logo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_InterfazLogo_screen_destroy(void)
{
    if(ui_InterfazLogo) lv_obj_del(ui_InterfazLogo);

    // NULL screen variables
    ui_InterfazLogo = NULL;
    ui_Logo = NULL;

}
